#!/bin/bash
NAME="app"
DIR=/home/httpd/nonexistentdomain.ru
USER=www-data
GROUP=www-data
WORKERS=2
BIND=unix:/home/httpd/nonexistentdomain.ru/gunicorn.sock
DJANGO_SETTINGS_MODULE=Esp12fScd30.settings
DJANGO_WSGI_MODULE=Esp12fScd30.wsgi
LOG_LEVEL=error
cd $DIR
source env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH
exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=gunicorn.log
